3 homework base lvl
harli40/mts-study-app pull request #4
Opened 2021-07-15 18:15 UTC by harli40

Отступы добавлены в ресурсы, кнопки навигации - просто imageview, отступы по бокам от экрана были взяты за 20 для всех элементов, вместо 20-22.

2021-07-16 12:13 UTC, maxlord requested changes

2021-07-16 12:13 UTC, maxlord commented on app/src/main/res/layout/activity_movie_details.xml
> +                android:layout_marginTop="@dimen/marg_genre_top"
genre_top_margin
и т.д. далее для остальных дименов.

2021-07-16 12:13 UTC, maxlord commented on app/src/main/res/values/paddings.xml
> -    <dimen name="pad_"></dimen>
Непонятно, зачем куча одинаковых ресурсов.

2021-07-16 12:13 UTC, maxlord commented on app/src/main/res/values/paddings.xml
> -    <dimen name="pad_"></dimen>
Лучше удали те ресурсы, которые не используешь. Да и отдельных paddings.xml не стоит создавать.
Обычно ты все ресурсы с размерами определяешь в dimens.xml, группируя их по экрану

<!--  Movie Screen  -->
<dimen...
...
и т.д.

2021-07-16 17:57 UTC, harli40 commented on app/src/main/res/values/paddings.xml
> -    <dimen name="pad_"></dimen>
пустые ресурсы случайно оставил, а имена поменял

2021-07-17 09:20 UTC, maxlord commented on app/src/main/res/values/paddings.xml
> -    <dimen name="pad_"></dimen>
Сделай коммит с исправлениями в этот

2021-07-17 09:24 UTC, maxlord requested changes

2021-07-17 09:24 UTC, maxlord commented on app/src/main/res/values/dimens.xml
> +    <dimen name="ic_bottom_views_padding">14dp</dimen>
ic_ в дименах не надо использовать
можно назвать так: base_view_padding

2021-07-17 12:35 UTC, harli40 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="ic_bottom_views_padding">14dp</dimen>
поправил

2021-07-17 14:40 UTC, harli40 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="ic_bottom_views_padding">14dp</dimen>
заметил, что убрал ic_ в дименах, но просто поменял название, а не через рефактор, поэтому в разметке не поменялось ничего. сейчас исправил окончательно

2021-07-20 07:46 UTC, maxlord requested changes
Нужно исправить пару замечаний по неймингу

2021-07-20 07:46 UTC, maxlord commented on app/src/main/res/layout/activity_movie_details.xml
> +                        android:layout_marginTop="@dimen/each_actor_name_top_margin"
each_ будет лишним тут
достаточно будет actor_name_top_margin

2021-07-20 07:46 UTC, maxlord commented on app/src/main/res/layout/activity_movie_details.xml
> +                        android:layout_marginEnd="@dimen/main_start_end_margin"
start_end - читается не очень
Лучше называть более осмысленно
Если это _end_margin, то назови его так: main_end_margin, и between тоже лишним кажется, star_margin - и так понятно, что это маржин для звезд, а между звездами или как-то еще - уже не так важно

2021-07-20 08:38 UTC, harli40 commented on app/src/main/res/layout/activity_movie_details.xml
> +                        android:layout_marginEnd="@dimen/main_start_end_margin"
Исправил. main_start_end_margin переименовал, но, возможно, стоило сделать отдельный марджин для начала и конца экрана, а не один общий?

2021-07-20 13:53 UTC, maxlord commented on app/src/main/res/layout/activity_movie_details.xml
> +                        android:layout_marginEnd="@dimen/main_start_end_margin"
Если они симметричны, то нет необходимости делать разные димены, достаточно одного. Обычно его называют horizontal_margin как-то так

2021-07-20 13:58 UTC, harli40 commented on app/src/main/res/layout/activity_movie_details.xml
> +                        android:layout_marginEnd="@dimen/main_start_end_margin"
Понял, поменяю значит на horizontal, через часа полтора к лекции как раз дома буду - сменю.

2021-07-20 15:49 UTC, harli40 commented on app/src/main/res/layout/activity_movie_details.xml
> +                        android:layout_marginEnd="@dimen/main_start_end_margin"
есть, сменил имя на horizontal

2021-07-20 21:11 UTC, maxlord approved these changes

2021-07-20 21:20 UTC, merged