4 homework
harli40/mts-study-app pull request #6
Opened 2021-07-22 23:58 UTC by harli40

- Не вышло углы скруглить у imageView фильма - думал через shape, но не получилось.
 - Вызываются тосты при нажатии на жанры и карточки фильмов.
 - DiffUtil работает при обновлении списка, по нажатию на иконку поиска, добавляются новые данные(просто для проверки работы обвновления данных)
 - Через ItemDecoration настроил отступы, с учетом первых и последних элементов ресайклера
 - Убрал передачу данных из констуктора адаптера
 - В альбомной ориентации все работает, но разметку нормальную не придумал - доделаю

2021-07-23 14:22 UTC, maxlord requested changes

2021-07-23 14:22 UTC, maxlord commented on app/src/main/java/ru/onopry/mtshomework/adapters/MovieAdapter.kt
> +                    movieRatingStar1.setBackgroundResource(R.drawable.ic_star_fill)
При бинде нужно обновлять все вьюшки, помнишь из лекции?

2021-07-23 14:22 UTC, maxlord commented on app/src/main/java/ru/onopry/mtshomework/data/features/diffUtils/GenresDiffUtilCallback.kt
> +        oldList[oldItemPosition] == newList[newItemPosition]
Тут нужно сравнивать по какому-нибудь аттрибуту.

2021-07-24 11:03 UTC, maxlord requested changes

2021-07-24 11:03 UTC, maxlord commented on app/src/main/res/layout/item_movie_card.xml
> +        android:id="@+id/movie_list_card_elem_film_image"
id вьюшек должны называться в camelCase, т.е. tvMoviewFilmImage.
И раз уж это разметка айтема, то не надо имя перегружать лишним неймингом list_card_elem.

2021-07-24 12:14 UTC, harli40 commented on app/src/main/res/layout/item_movie_card.xml
> +        android:id="@+id/movie_list_card_elem_film_image"
А существует практика указывать расположение вьюхи/лейауты в id? Например у нас же есть разметка активити с деталями фильма с 3 дз и разметка с текущей дз, где список фильмов. И там и там есть повторяющиеся вьюшки. Можно ли, например, для названия фильма указывать айдишники "detailsFilmImage" "itemFilmImage"?
И префикс "tv" в tvMoviewFilmImage, вашем комментарии, означает textView? Или как то иначе именовать их?

2021-07-26 10:13 UTC, maxlord requested changes

2021-07-26 10:13 UTC, maxlord commented on app/src/main/java/ru/onopry/mtshomework/adapters/MovieAdapter.kt
> +        private val movieRatingStar1: View = itemView.findViewById(R.id.vMovieitemStar1)
iv?

2021-07-26 10:13 UTC, maxlord commented on app/src/main/java/ru/onopry/mtshomework/adapters/MovieAdapter.kt
> +        private val movieRatingStar1: View = itemView.findViewById(R.id.vMovieitemStar1)
Видимо имелось ввиду v - view. Поэтому лучше так не сокращать, для вью
viewMovieStar1. Item тут будет лишним.

2021-07-29 20:54 UTC, merged